### ISSUE TITLE
X-Plane Freezing

### ISSUE THREAD

**Issue by TheFiddler14** [benrussell/Gizmo64.com#3]
Gizmo64 appears to be stalling out X-Plane from loading with the most recent X-Plane update.  The issue started immediately after I made the most recent update.  I reinstalled a fresh latest copy of X-Plane, verified it worked, and then started adding back in plug-ins.  This confirmed that Gizmo64 is the culprit.

Attached is a Log.txt from when the issued occurred.  
[Log.txt](https://github.com/benrussell/Gizmo64.com/files/6004305/Log.txt)

Also attached below is a GizmoLog.txt file from this morning when it occurred.
[GizmoLog.txt](https://github.com/benrussell/Gizmo64.com/files/6004275/GizmoLog.txt)

Please let me know if you need any further information.  I'm happy to provide whatever I can to help.

Regards - Derek (TheFiddler14)

**Comment by benrussell** [comment]
1. Version of Gizmo listed in Log.txt file is over 2 years old.

2. Try removing: Loaded: C:\X-Plane 11/Resources/plugins/SAM/win_x64/SAM.xpl (stairportsceneries.plugin.aos).

3. Due to the nature of X-Plane and it's plugin SDK, a failure triggered in a given plugin may not be _caused_ by that plugin.
Plugin A is free to write over the memory areas and values used by Plugin B.
When only A is present it's fine.
When only B is present it's fine.
When A and B are installed, things crash.

Cheers.

**Comment by TheFiddler14** [comment]
Thanks Ben - I'll do some further experimenting.  The current SMP and RWC add-ons must be using an old Gizmo version as that's where it came from.  I'll keep you posted once I get some more results.  I appreciate from your explanation that it may not be Gizmo that's causing the issue necessarily.  Thanks for the clarity on that.

Derek

**Comment by TheFiddler14** [comment]
> Thanks Ben - I'll do some further experimenting. The current SMP and RWC add-ons must be using an old Gizmo version as that's where it came from. I'll keep you posted once I get some more results. I appreciate from your explanation that it may not be Gizmo that's causing the issue necessarily. Thanks for the clarity on that.
> 
> Derek

I installed the updated Gizmo64 plugin after installing SMP and RWC (to overwrite the old copy they include in their installers) and everything seems to be working fine now.  Thanks for the help!
